### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by ntzwilly** [wuyepabdul/javascript-capstone#21]
https://github.com/wuyepabdul/javascript-capstone.git 

We are two working on this project

**Comment by mke2111** [comment]
### Hi @ntzwilly & @wuyepabdul, 

Your milestone is complete!  There is nothing else to say other than :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issues thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
